### ISSUE TITLE
HDMI won't work over usb type C

### ISSUE THREAD

**Issue by luka3110** [t-shao/-Hackintosh-OMEN_by_HP_Laptop_15-ce0xx#1]
I have almost the same laptop, except I have i7 7700HQ. I used same parameters for setting up iGPU. And external display won't work over standard HDMI port, so I bought usb type C dongle with HDMI, and two usb 3.0 (d-link), and again it didn't worked.

**Comment by DrJedikiah** [comment]
Yeah same here, it's actually a DP port but still no luck

**Comment by t-shao** [comment]
Actually I have no idea why it doesn't work for you but maybe I'll update my configs a few days later, and you can have a try then.

**Comment by DrJedikiah** [comment]
> Actually I have no idea why it doesn't work for you but maybe I'll update my configs a few days later, and you can have a try then.

I'll be waiting for it, thanks

**Comment by t-shao** [comment]
configs updated :)
