### ISSUE TITLE
Microphone with Intel Array

### ISSUE THREAD

**Issue by richibrics** [t-shao/-Hackintosh-OMEN_by_HP_Laptop_15-ce0xx#2]
Hi, how did you manage to get the microphone to work ? Have you used ACPI/Kext/Patches ?
I have a similar audio preset but my microphone doesn't recognize any sound so maybe your solution works also for me.

Thanks !

**Comment by t-shao** [comment]
I use the AppleALC.kext and inject the layout-id=3 via DeviceProperties. Hope it works for you.
