### ISSUE TITLE
Battery Calibration

### ISSUE THREAD

**Issue by retrohog** [t-shao/-Hackintosh-OMEN_by_HP_Laptop_15-ce0xx#4]
Hey I do have same laptop but a little bit of different hardware if you don't mind would you help me to fix the battery problems
Like how much hours of sot you are getting on bigsur? Am getting around 1:30 to 2 hours almost can we optimise that even more?
And can you share your discord or telegram id I need a little help if you don't mind

Here's my EFI folder-https://drive.google.com/file/d/1dt_zAUhfMQ4OxlS-mxxspA60i4Ij1kSr/view?usp=sharing

Thanks

**Comment by t-shao** [comment]
Actually, the battery performance I get is not satisfactory as well, especially after waking up from the sleep mode, similar to your situation, around 1.5 to 2 hours. However, interestingly, I found that the sot can be greatly better on cold boot. So maybe there's something wrong in the power state of some component on sleep or wake.

**Comment by retrohog** [comment]
I need a bit help could you ping me over discord some strange issue xD

Discord id-ＳＴＩＴＩＯＵＳ#2031

**Comment by retrohog** [comment]
> Actually, the battery performance I get is not satisfactory as well, especially after waking up from the sleep mode, similar to your situation, around 1.5 to 2 hours. However, interestingly, I found that the sot can be greatly better on cold boot. So maybe there's something wrong in the power state of some component on sleep or wake.

Could you update the efi folder with latest? and am using your battery patch but it isn't working can you tell me how to sync this patch with my efi folder
